services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      ports: [5432:5432]

  airflow-webserver:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__EXECUTOR:
      ARIFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__RBAC: 'True'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./snowflake:/opt/airflow/snowflake
    ports: [8080:8080]
    depends_on: [postgres]
  
  airflow-scheduler:
    image: apache/airflow:2.7.1
    depends_on: [airflow-webserver,postgres]
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      ARIFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags